name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  issues: write
  pull-requests: write
  contents: read
  # metadata: read  # これも追加

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      # ⭐ このステップを追加
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # オプション: カスタムトリガーフレーズ（デフォルト: @claude）
          # trigger_phrase: "/claude"
          # オプション: Issueのアサイニートリガー
          # assignee_trigger: "claude"
